// SPDX-FileCopyrightText: 2026 rlauuzo
// SPDX-License-Identifier: GPL-3.0-only

namespace IntroSkipper.Tests;

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using IntroSkipper.Configuration;
using IntroSkipper.Data;
using IntroSkipper.Db;
using IntroSkipper.Helper;
using IntroSkipper.Manager;
using IntroSkipper.ScheduledTasks;
using MediaBrowser.Model.Entities;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Xunit;

public sealed class TestLegacyAnalysisCompatibility
{
    [Theory]
    [InlineData(AnalysisMode.Introduction, false, false, "D65089C5988650A1")]
    [InlineData(AnalysisMode.Introduction, true, false, "8DBCDDC0D7121940")]
    [InlineData(AnalysisMode.Credits, false, false, "21D032F917DBB286")]
    [InlineData(AnalysisMode.Credits, false, true, "F54591829B4EE31B")]
    [InlineData(AnalysisMode.Credits, true, false, "C7BDDBC293143FF9")]
    [InlineData(AnalysisMode.Credits, true, true, "E12710E4AFCAF91D")]
    [InlineData(AnalysisMode.Recap, false, false, "00AC4A136129A4A7")]
    [InlineData(AnalysisMode.Recap, true, false, "3E22D6A17CDA5178")]
    public void LegacyHashes_MatchOriginal1011Hasher(AnalysisMode mode, bool available, bool alternative, string expected)
    {
        Assert.Equal(expected, LegacyAnalysisCompatibility.AnalysisHash(new PluginConfiguration(), mode, AnalyzerAction.Default, available, alternative));
    }

    /// <summary>
    /// Expected values were generated by running ConfigHasher.cs from the published
    /// 10.11/v1.10.11.22 and 10.11/v1.10.11.23 tags, independently of this helper.
    /// </summary>
    [Theory]
    [InlineData(22, AnalysisMode.Introduction, false, false, "CED1FA8430C9A3E1")]
    [InlineData(22, AnalysisMode.Introduction, true, false, "C554CFE8FD7F689F")]
    [InlineData(22, AnalysisMode.Credits, false, false, "4310FF2532492CCD")]
    [InlineData(22, AnalysisMode.Credits, false, true, "081AF31FA0B40353")]
    [InlineData(22, AnalysisMode.Credits, true, false, "B94D4918E2CCA65E")]
    [InlineData(22, AnalysisMode.Credits, true, true, "2F0ECC8A7DCA167C")]
    [InlineData(22, AnalysisMode.Preview, false, false, "1529110AB90D09C8")]
    [InlineData(22, AnalysisMode.Preview, true, false, "1529110AB90D09C8")]
    [InlineData(22, AnalysisMode.Recap, false, false, "3BBBB515BBE60873")]
    [InlineData(22, AnalysisMode.Recap, true, false, "8A50014E7585B074")]
    [InlineData(22, AnalysisMode.Commercial, false, false, "E795D9EA95F28728")]
    [InlineData(22, AnalysisMode.Commercial, true, false, "E795D9EA95F28728")]
    [InlineData(23, AnalysisMode.Introduction, false, false, "CED1FA8430C9A3E1")]
    [InlineData(23, AnalysisMode.Introduction, true, false, "C554CFE8FD7F689F")]
    [InlineData(23, AnalysisMode.Credits, false, false, "4AD4F59A6772AEEC")]
    [InlineData(23, AnalysisMode.Credits, false, true, "03E9B9704F41C057")]
    [InlineData(23, AnalysisMode.Credits, true, false, "1EB53C075A0FB188")]
    [InlineData(23, AnalysisMode.Credits, true, true, "F79EF59308B6028D")]
    [InlineData(23, AnalysisMode.Preview, false, false, "1529110AB90D09C8")]
    [InlineData(23, AnalysisMode.Preview, true, false, "1529110AB90D09C8")]
    [InlineData(23, AnalysisMode.Recap, false, false, "70F97A7C32A01543")]
    [InlineData(23, AnalysisMode.Recap, true, false, "5D8F5EAE0A1F83A8")]
    [InlineData(23, AnalysisMode.Commercial, false, false, "E795D9EA95F28728")]
    [InlineData(23, AnalysisMode.Commercial, true, false, "E795D9EA95F28728")]
    public void OlderHashes_MatchPublishedReleaseHashers(int release, AnalysisMode mode, bool available, bool alternative, string expected)
    {
        Assert.Equal(expected, LegacyAnalysisCompatibility.AnalysisHash(new PluginConfiguration(), mode, AnalyzerAction.Default, available, alternative, release));
    }

    [Theory]
    [InlineData(AnalysisMode.Introduction, false)]
    [InlineData(AnalysisMode.Credits, false)]
    [InlineData(AnalysisMode.Credits, true)]
    [InlineData(AnalysisMode.Recap, false)]
    [InlineData(AnalysisMode.Introduction, false, 22)]
    [InlineData(AnalysisMode.Credits, false, 22, false)]
    [InlineData(AnalysisMode.Credits, true, 22, false)]
    [InlineData(AnalysisMode.Recap, false, 22)]
    [InlineData(AnalysisMode.Preview, false, 22, false)]
    [InlineData(AnalysisMode.Commercial, false, 22)]
    [InlineData(AnalysisMode.Introduction, false, 23)]
    [InlineData(AnalysisMode.Credits, false, 23, false)]
    [InlineData(AnalysisMode.Credits, true, 23, false)]
    [InlineData(AnalysisMode.Recap, false, 23)]
    [InlineData(AnalysisMode.Preview, false, 23, false)]
    [InlineData(AnalysisMode.Commercial, false, 23)]
    public async Task ImportedCompletedSeason_AdoptsHashesWithoutDetection(AnalysisMode mode, bool alternative, int release = 24, bool compatible = true)
    {
        var config = new PluginConfiguration { ReanalyzeSettledSeasons = true };
        using var pluginScope = EntrypointTestHelpers.CreatePluginScope(config);
        var directory = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(directory);
        var legacyPath = Path.Combine(directory, "introskipper.db");
        var databasePath = Path.Combine(directory, "introskipper-v2.db");
        var mediaPath = Path.Combine(directory, "episode.mkv");
        await File.WriteAllBytesAsync(mediaPath, []);
        try
        {
            var ids = new[] { Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid() };
            var seasonId = Guid.NewGuid();
            var action = AnalyzerAction.Chapter;
            var legacyHash = LegacyAnalysisCompatibility.AnalysisHash(config, mode, action, true, alternative, release);
            var currentHash = ConfigHasher.Analysis(config, mode, action, true);
            var episodeIdsJson = JsonSerializer.Serialize(ids);
            LegacySchemaFixtures.CreateV5(
                legacyPath,
                [new(ids[0], 10, 60, (int)mode, ConfigHash: legacyHash), new(ids[2], 15, 65, (int)mode, IsUserProvided: true)],
                [new(seasonId, (int)mode, (int)action, episodeIdsJson, legacyHash, episodeIdsJson)]);
            var legacyBytes = await File.ReadAllBytesAsync(legacyPath);
            var database = DatabaseTestHelpers.CreateSegmentDatabase(databasePath);
            await database.InitializeAsync();
            var original = Assert.Single(await database.GetSegmentsAsync(ids[0]));
            database = DatabaseTestHelpers.CreateSegmentDatabase(databasePath);
            var items = ids.Select(id => JellyfinItems.Episode(id, Guid.NewGuid(), seasonId, path: mediaPath)).ToArray();
            var library = EntrypointTestHelpers.FakeLibraryManager.Create([JellyfinItems.Folder("Media")], items);
            EntrypointTestHelpers.SetPrivateField(Plugin.Instance!, "_libraryManager", library);
            var ffmpeg = new StubFFmpegService { VersionCheck = () => true };
            var queue = new QueueManager(NullLogger<QueueManager>.Instance, library, null!, null!, ffmpeg, database);
            var candidates = ids.Select(id => new QueuedEpisode
            {
                EpisodeId = id,
                SeasonId = seasonId,
                SeasonNumber = 1,
                DateAdded = DateTime.UtcNow.AddDays(-30),
            }).ToArray();

            var verified = await queue.VerifyQueueAsync(candidates, [mode]);

            Assert.Equal(3, verified.Count);
            Assert.Equal(compatible ? EpisodeState.Analyzed : EpisodeState.NotAnalyzed, verified[0].GetAnalyzed(mode));
            Assert.Equal(compatible ? EpisodeState.NoSegments : EpisodeState.NotAnalyzed, verified[1].GetAnalyzed(mode));
            Assert.Equal(EpisodeState.UserProvided, verified[2].GetAnalyzed(mode));
            var states = await database.GetSettleReanalysisStatesAsync(seasonId);
            Assert.True(SeasonReanalysisPlanner.IsSettledForReanalysis(verified, config, DateTime.UtcNow));
            Assert.Empty(SeasonReanalysisPlanner.GetSettleReanalysisModes(states, ids, [mode], true));
            if (compatible)
            {
                var task = new BaseItemAnalyzerTask(NullLogger.Instance, NullLoggerFactory.Instance, null!, ffmpeg, null!, database);
                await task.AnalyzeItemsAsync(verified, mode, action, true, CancellationToken.None);
            }

            Assert.Equal(0, ffmpeg.FingerprintCalls);
            Assert.Equal(0, ffmpeg.CreditsScanCalls);
            Assert.Equal(0, ffmpeg.RangeScanCalls);
            Assert.Equal(0, ffmpeg.VisualScanCalls);
            Assert.Equal(0, ffmpeg.IntervalScanCalls);

            var segment = Assert.Single(await database.GetSegmentsAsync(ids[0]));
            Assert.Equal(original.Id, segment.Id);
            Assert.Equal(original.StartTicks, segment.StartTicks);
            Assert.Equal(original.EndTicks, segment.EndTicks);
            Assert.Equal(original.UpdatedAt, segment.UpdatedAt);
            Assert.Equal(SegmentSource.Unknown, segment.Source);
            var expectedHash = compatible ? currentHash : legacyHash;
            Assert.Equal(expectedHash, segment.ConfigHash);
            Assert.Equal(0, await database.CleanStaleAutomaticSegmentsAsync(ids, mode, expectedHash));
            var snapshot = await database.GetSeasonQueueSnapshotAsync(seasonId, ids);
            Assert.All(snapshot.AnalyzedConfigHashes.Values, hash => Assert.Equal(expectedHash, hash));
            Assert.False(await LegacyAnalysisCompatibility.UpgradeAsync(database, snapshot, config));
            Assert.Equal(legacyBytes, await File.ReadAllBytesAsync(legacyPath));

            await using var db = DatabaseTestHelpers.CreateSegmentContext(databasePath);
            Assert.Empty(await db.ProjectionQueue.ToListAsync());
        }
        finally
        {
            DatabaseTestHelpers.DeleteSqliteFiles(databasePath);
            DatabaseTestHelpers.DeleteSqliteFiles(legacyPath);
            Directory.Delete(directory, true);
        }
    }

    [Theory]
    [InlineData(AnalysisMode.Introduction, "language")]
    [InlineData(AnalysisMode.Introduction, "channels")]
    [InlineData(AnalysisMode.Introduction, "duration")]
    [InlineData(AnalysisMode.Introduction, "action")]
    [InlineData(AnalysisMode.Credits, "legacy")]
    [InlineData(AnalysisMode.Credits, "threshold")]
    [InlineData(AnalysisMode.Recap, "cold-open")]
    public async Task ChangedSettings_DoNotAdoptLegacyCompletion(AnalysisMode mode, string change)
    {
        using var temp = new TempSegmentDb();
        var config = new PluginConfiguration();
        var id = Guid.NewGuid();
        var seasonId = Guid.NewGuid();
        var legacyHash = LegacyAnalysisCompatibility.AnalysisHash(config, mode, AnalyzerAction.Default, true, false);
        await temp.Database.MarkItemsAnalyzedAsync(mode, [id], legacyHash);
        switch (change)
        {
            case "language": config.PreferredAudioLanguage = "eng"; break;
            case "channels": config.PreferAudioStreamWithMostChannels = false; break;
            case "duration": config.MinimumIntroDuration++; break;
            case "action": await temp.Database.SetAnalyzerActionAsync(seasonId, new Dictionary<AnalysisMode, AnalyzerAction> { [mode] = AnalyzerAction.Chapter }); break;
            case "legacy": config.UseLegacyBlackFrameAnalyzer = true; break;
            case "threshold": config.BlackFrameThreshold++; break;
            case "cold-open": config.AnchorRecapToColdOpen = true; break;
            default: throw new ArgumentOutOfRangeException(nameof(change));
        }

        var snapshot = await temp.Database.GetSeasonQueueSnapshotAsync(seasonId, [id]);

        Assert.False(await LegacyAnalysisCompatibility.UpgradeAsync(temp.Database, snapshot, config));
        var candidate = new QueuedEpisode { EpisodeId = id };
        new QueueVerifier(config, [mode], snapshot, true).Classify(candidate);
        Assert.Equal(EpisodeState.NotAnalyzed, candidate.GetAnalyzed(mode));
    }

    [Theory]
    [InlineData(AnalysisMode.Introduction, "offset")]
    [InlineData(AnalysisMode.Credits, "offset")]
    [InlineData(AnalysisMode.Recap, "offset")]
    [InlineData(AnalysisMode.Preview, "offset")]
    [InlineData(AnalysisMode.Commercial, "offset")]
    [InlineData(AnalysisMode.Credits, "minimum")]
    [InlineData(AnalysisMode.Preview, "derived")]
    public async Task SettingsAbsentFromOlderHashes_BlockOlderAdoption(AnalysisMode mode, string setting)
    {
        using var temp = new TempSegmentDb();
        var config = new PluginConfiguration();
        var ids = new[] { Guid.NewGuid(), Guid.NewGuid() };
        for (var i = 0; i < ids.Length; i++)
        {
            var hash = LegacyAnalysisCompatibility.AnalysisHash(config, mode, AnalyzerAction.Default, true, false, 22 + i);
            await temp.Database.MarkItemsAnalyzedAsync(mode, [ids[i]], hash);
        }

        switch (setting)
        {
            case "offset": config.IncludeIntroStartOffsetWhenSnapping = true; break;
            case "minimum": config.MinimumIntroDuration++; break;
            case "derived": config.AnimePreviewFromCreditsEnd = true; break;
            default: throw new ArgumentOutOfRangeException(nameof(setting));
        }

        var snapshot = await temp.Database.GetSeasonQueueSnapshotAsync(Guid.NewGuid(), ids);

        Assert.False(await LegacyAnalysisCompatibility.UpgradeAsync(temp.Database, snapshot, config));
        foreach (var id in ids)
        {
            var candidate = new QueuedEpisode { EpisodeId = id };
            new QueueVerifier(config, [mode], snapshot, true).Classify(candidate);
            Assert.Equal(EpisodeState.NotAnalyzed, candidate.GetAnalyzed(mode));
        }
    }

    [Theory]
    [InlineData(AnalysisMode.Preview)]
    [InlineData(AnalysisMode.Commercial)]
    public async Task ChapterOnlyModes_AdoptOlderHashesRegardlessOfAudioSelection(AnalysisMode mode)
    {
        using var temp = new TempSegmentDb();
        var config = new PluginConfiguration { PreferredAudioLanguage = "eng", PreferAudioStreamWithMostChannels = false };
        var id = Guid.NewGuid();
        var hash = LegacyAnalysisCompatibility.AnalysisHash(config, mode, AnalyzerAction.Default, true, false, 22);
        await temp.Database.MarkItemsAnalyzedAsync(mode, [id], hash);
        var snapshot = await temp.Database.GetSeasonQueueSnapshotAsync(Guid.NewGuid(), [id]);

        Assert.Equal(mode == AnalysisMode.Commercial, await LegacyAnalysisCompatibility.UpgradeAsync(temp.Database, snapshot, config));

        snapshot = await temp.Database.GetSeasonQueueSnapshotAsync(Guid.NewGuid(), [id]);
        Assert.Equal(mode == AnalysisMode.Commercial ? ConfigHasher.Analysis(config, mode, AnalyzerAction.Default, true) : hash, snapshot.AnalyzedConfigHashes[(id, mode)]);
    }

    [Theory]
    [InlineData(22)]
    [InlineData(23)]
    [InlineData(24)]
    public async Task DisablingDerivedPreviews_RetiresImportedPreview(int release)
    {
        var oldConfig = new PluginConfiguration { AnimePreviewFromCreditsEnd = true };
        var config = new PluginConfiguration { AnimePreviewFromCreditsEnd = false };
        using var pluginScope = EntrypointTestHelpers.CreatePluginScope(config, Array.Empty<ChapterInfo>());
        var directory = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(directory);
        var legacyPath = Path.Combine(directory, "introskipper.db");
        var databasePath = Path.Combine(directory, "introskipper-v2.db");
        var mediaPath = Path.Combine(directory, "episode.mkv");
        await File.WriteAllBytesAsync(mediaPath, []);
        try
        {
            var id = Guid.NewGuid();
            var seasonId = Guid.NewGuid();
            var previewHash = LegacyAnalysisCompatibility.AnalysisHash(oldConfig, AnalysisMode.Preview, AnalyzerAction.Default, true, false, release);
            var creditsHash = LegacyAnalysisCompatibility.AnalysisHash(oldConfig, AnalysisMode.Credits, AnalyzerAction.Default, true, false, release);
            var ids = JsonSerializer.Serialize(new[] { id });
            LegacySchemaFixtures.CreateV5(
                legacyPath,
                [new(id, 1200, 1260, (int)AnalysisMode.Credits, ConfigHash: creditsHash), new(id, 1260, 1320, (int)AnalysisMode.Preview, ConfigHash: creditsHash)],
                [new(seasonId, (int)AnalysisMode.Preview, (int)AnalyzerAction.Default, ids, previewHash, ids), new(seasonId, (int)AnalysisMode.Credits, (int)AnalyzerAction.Default, ids, creditsHash, ids)]);
            var database = DatabaseTestHelpers.CreateSegmentDatabase(databasePath);
            await database.InitializeAsync();
            var library = EntrypointTestHelpers.CreateLibraryManager(JellyfinItems.Episode(id, Guid.NewGuid(), seasonId, path: mediaPath));
            EntrypointTestHelpers.SetPrivateField(Plugin.Instance!, "_libraryManager", library);
            var ffmpeg = new StubFFmpegService { VersionCheck = () => true };
            var candidate = new QueuedEpisode { EpisodeId = id, SeasonId = seasonId, SeasonNumber = 1, Duration = 1320, Category = QueuedMediaCategory.AnimeEpisode };
            var queue = new QueueManager(NullLogger<QueueManager>.Instance, library, null!, null!, ffmpeg, database);

            Assert.Single(await queue.VerifyQueueAsync([candidate], [AnalysisMode.Preview]));
            Assert.Equal(EpisodeState.NotAnalyzed, candidate.GetAnalyzed(AnalysisMode.Preview));
            var task = new BaseItemAnalyzerTask(NullLogger.Instance, NullLoggerFactory.Instance, null!, ffmpeg, null!, database);
            await task.AnalyzeItemsAsync([candidate], AnalysisMode.Preview, AnalyzerAction.Default, true, CancellationToken.None);

            Assert.Equal(AnalysisMode.Credits, Assert.Single(await database.GetSegmentsAsync(id)).Type);
            var snapshot = await database.GetSeasonQueueSnapshotAsync(seasonId, [id]);
            Assert.Equal(ConfigHasher.Analysis(config, AnalysisMode.Preview, AnalyzerAction.Default, true), snapshot.AnalyzedConfigHashes[(id, AnalysisMode.Preview)]);
            Assert.Equal(0, ffmpeg.FingerprintCalls);
            Assert.Equal(0, ffmpeg.CreditsScanCalls);
        }
        finally
        {
            DatabaseTestHelpers.DeleteSqliteFiles(databasePath);
            DatabaseTestHelpers.DeleteSqliteFiles(legacyPath);
            Directory.Delete(directory, true);
        }
    }

    [Theory]
    [InlineData(22, false)]
    [InlineData(22, true)]
    [InlineData(23, false)]
    [InlineData(23, true)]
    [InlineData(24, false)]
    [InlineData(24, true)]
    public async Task ReturningCreditsMinimumToDefault_DoesNotAdoptOldNegativeResult(int release, bool alternative)
    {
        using var temp = new TempSegmentDb();
        var oldConfig = new PluginConfiguration { MinimumIntroDuration = 60 };
        var config = new PluginConfiguration();
        var id = Guid.NewGuid();
        var seasonId = Guid.NewGuid();
        var hash = LegacyAnalysisCompatibility.AnalysisHash(oldConfig, AnalysisMode.Credits, AnalyzerAction.Default, true, alternative, release);
        await temp.Database.MarkItemsAnalyzedAsync(AnalysisMode.Credits, [id], hash);
        var snapshot = await temp.Database.GetSeasonQueueSnapshotAsync(seasonId, [id]);

        Assert.False(await LegacyAnalysisCompatibility.UpgradeAsync(temp.Database, snapshot, config));

        snapshot = await temp.Database.GetSeasonQueueSnapshotAsync(seasonId, [id]);
        Assert.Equal(hash, snapshot.AnalyzedConfigHashes[(id, AnalysisMode.Credits)]);
        var candidate = new QueuedEpisode { EpisodeId = id };
        new QueueVerifier(config, [AnalysisMode.Credits], snapshot, true).Classify(candidate);
        Assert.Equal(EpisodeState.NotAnalyzed, candidate.GetAnalyzed(AnalysisMode.Credits));
    }

    [Theory]
    [InlineData(false, false, EpisodeState.NoSegments)]
    [InlineData(false, true, EpisodeState.NotAnalyzed)]
    [InlineData(true, false, EpisodeState.NoSegments)]
    [InlineData(true, true, EpisodeState.NoSegments)]
    public async Task CapabilityChanges_KeepExistingInvalidationDirection(bool previousAvailable, bool available, EpisodeState expected)
    {
        using var temp = new TempSegmentDb();
        var config = new PluginConfiguration();
        var id = Guid.NewGuid();
        var seasonId = Guid.NewGuid();
        const AnalysisMode mode = AnalysisMode.Introduction;
        await temp.Database.MarkItemsAnalyzedAsync(mode, [id], LegacyAnalysisCompatibility.AnalysisHash(config, mode, AnalyzerAction.Default, previousAvailable, false));
        var snapshot = await temp.Database.GetSeasonQueueSnapshotAsync(seasonId, [id]);
        Assert.True(await LegacyAnalysisCompatibility.UpgradeAsync(temp.Database, snapshot, config));
        snapshot = await temp.Database.GetSeasonQueueSnapshotAsync(seasonId, [id]);
        var candidate = new QueuedEpisode { EpisodeId = id };

        new QueueVerifier(config, [mode], snapshot, available).Classify(candidate);

        Assert.Equal(expected, candidate.GetAnalyzed(mode));
        config.MinimumIntroDuration++;
        Assert.False(await LegacyAnalysisCompatibility.UpgradeAsync(temp.Database, snapshot, config));
        candidate = new QueuedEpisode { EpisodeId = id };
        new QueueVerifier(config, [mode], snapshot, true).Classify(candidate);
        Assert.Equal(EpisodeState.NotAnalyzed, candidate.GetAnalyzed(mode));
    }

    [Fact]
    public async Task UnknownHashesAndUnrecordedModes_RemainPending()
    {
        using var temp = new TempSegmentDb();
        var config = new PluginConfiguration();
        var ids = new[] { Guid.NewGuid(), Guid.NewGuid(), Guid.NewGuid() };
        const AnalysisMode mode = AnalysisMode.Introduction;
        await temp.Database.MarkItemsAnalyzedAsync(mode, [ids[0]], "unrecognized-hash");
        await temp.Database.MarkItemsAnalyzedAsync(mode, [ids[1]], string.Empty);
        var snapshot = await temp.Database.GetSeasonQueueSnapshotAsync(Guid.NewGuid(), ids);

        Assert.False(await LegacyAnalysisCompatibility.UpgradeAsync(temp.Database, snapshot, config));

        foreach (var id in ids)
        {
            var candidate = new QueuedEpisode { EpisodeId = id };
            new QueueVerifier(config, [mode, AnalysisMode.Recap], snapshot, true).Classify(candidate);
            Assert.Equal(EpisodeState.NotAnalyzed, candidate.GetAnalyzed(mode));
            Assert.Equal(EpisodeState.NotAnalyzed, candidate.GetAnalyzed(AnalysisMode.Recap));
        }
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public async Task StaleSnapshot_DoesNotRestoreResetOrReanalyzedRecords(bool reanalyzed)
    {
        using var temp = new TempSegmentDb();
        var config = new PluginConfiguration();
        var id = Guid.NewGuid();
        const AnalysisMode mode = AnalysisMode.Introduction;
        var legacyHash = LegacyAnalysisCompatibility.AnalysisHash(config, mode, AnalyzerAction.Default, true, false);
        await temp.Database.MarkItemsAnalyzedAsync(mode, [id], legacyHash);
        var snapshot = await temp.Database.GetSeasonQueueSnapshotAsync(Guid.NewGuid(), [id]);
        await temp.Database.ResetItemsForReanalysisAsync([id], [mode]);
        if (reanalyzed)
        {
            await temp.Database.MarkItemsAnalyzedAsync(mode, [id], "newer-analysis");
        }

        Assert.False(await LegacyAnalysisCompatibility.UpgradeAsync(temp.Database, snapshot, config));

        await using var db = temp.Context();
        var rows = await db.AnalyzedItems.ToListAsync();
        if (reanalyzed)
        {
            Assert.Equal("newer-analysis", Assert.Single(rows).ConfigHash);
        }
        else
        {
            Assert.Empty(rows);
        }
    }

    [Fact]
    public async Task HashAdoption_UpdatesOnlyMatchingActiveAutomaticSegmentsAndIsAtomic()
    {
        using var temp = new TempSegmentDb();
        var id = Guid.NewGuid();
        var otherId = Guid.NewGuid();
        const AnalysisMode mode = AnalysisMode.Credits;
        await temp.Database.MarkItemsAnalyzedAsync(mode, [id], "old");
        await using var db = temp.Context();
        var automatic = new DbSegment(id, mode, 10, 20, SegmentSource.Unknown, "old");
        var derived = new DbSegment(id, AnalysisMode.Preview, 20, 30, SegmentSource.CreditsDerived, "old");
        DbSegment[] untouched =
        [
            new(id, mode, 30, 40, SegmentSource.User, "old"),
            new(id, mode, 40, 50, SegmentSource.Unknown, "old") { State = SegmentState.Suppressed },
            new(id, mode, 50, 60, SegmentSource.Unknown, "different"),
            new(id, AnalysisMode.Introduction, 0, 10, SegmentSource.Unknown, "old"),
            new(otherId, mode, 10, 20, SegmentSource.Unknown, "old"),
        ];
        db.Segments.AddRange([automatic, derived, .. untouched]);
        await db.SaveChangesAsync();
        db.ChangeTracker.Clear();
        await db.Database.ExecuteSqlRawAsync("CREATE TRIGGER FailAdoption BEFORE UPDATE ON AnalyzedItems BEGIN SELECT RAISE(ABORT, 'test failure'); END");

        await Assert.ThrowsAsync<SqliteException>(() => temp.Database.UpgradeAnalysisHashAsync(mode, [id, otherId], "old", "current"));

        Assert.Equal("old", (await db.Segments.SingleAsync(s => s.Id == automatic.Id)).ConfigHash);
        Assert.Equal("old", (await db.AnalyzedItems.SingleAsync()).ConfigHash);
        db.ChangeTracker.Clear();
        await db.Database.ExecuteSqlRawAsync("DROP TRIGGER FailAdoption");
        Assert.Equal(1, await temp.Database.UpgradeAnalysisHashAsync(mode, [id, otherId], "old", "current"));
        var rows = await db.Segments.AsNoTracking().ToDictionaryAsync(s => s.Id);
        Assert.Equal("current", rows[automatic.Id].ConfigHash);
        Assert.Equal("current", rows[derived.Id].ConfigHash);
        Assert.All(untouched, original => Assert.Equal(original.ConfigHash, rows[original.Id].ConfigHash));
        Assert.Empty(await db.ProjectionQueue.ToListAsync());
    }
}
