# Script to add SPDX-FileCopyrightText headers - skip bots, merge authors, skip auto-generated
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$env:LANG = "en_US.UTF-8"

$csFiles = Get-ChildItem -Recurse -Filter "*.cs" -File | Where-Object { $_.FullName -notmatch "\\obj\\" }

# Bots to skip
$botsToSkip = @("Copilot", "github-actions[bot]", "dependabot[bot]")

# Authors to merge (treat as same person)
$authorsToMerge = @{
    "rlauu" = "rlauuzo"
}

foreach ($file in $csFiles) {
    $relativePath = $file.FullName.Replace((Get-Location).Path + "\", "").Replace("\", "/")

    # Check if file starts with auto-generated comment
    $firstLines = Get-Content $file.FullName -Encoding UTF8 -TotalCount 2
    if ($firstLines -match "// <auto-generated />") {
        Write-Host "Skipping auto-generated: $relativePath"
        continue
    }

    Write-Host "Processing: $relativePath"

    # Get all commits with author and date - use UTF-8 encoding
    $commits = git log --follow --format="%an|%ad" --date=short -- $relativePath 2>$null

    # Build a hashmap of author -> year range, merging similar authors
    $authorYears = @{}
    foreach ($line in $commits) {
        $parts = $line -split '\|'
        $author = $parts[0]

        # Skip bots
        if ($botsToSkip -contains $author) {
            continue
        }

        # Merge authors
        if ($authorsToMerge.ContainsKey($author)) {
            $author = $authorsToMerge[$author]
        }

        $date = $parts[1]
        $year = [int]$date.Substring(0, 4)

        if (-not $authorYears.ContainsKey($author)) {
            $authorYears[$author] = @{FirstYear = $year; LastYear = $year}
        }
        else {
            if ($year -lt $authorYears[$author].FirstYear) {
                $authorYears[$author].FirstYear = $year
            }
            if ($year -gt $authorYears[$author].LastYear) {
                $authorYears[$author].LastYear = $year
            }
        }
    }

    # Sort authors by first year (oldest first)
    $sortedAuthors = $authorYears.GetEnumerator() | Sort-Object { $_.Value.FirstYear } | ForEach-Object { $_.Key }

    if ($sortedAuthors.Count -eq 0) {
        Write-Host "  No human authors found, skipping..."
        continue
    }

    Write-Host "  Human authors: $($sortedAuthors.Count)"

    # Read file content
    $content = Get-Content $file.FullName -Raw -Encoding UTF8

    # Remove existing SPDX-FileCopyrightText lines and license line
    $lines = $content -split "`r?`n"
    $newLines = @()
    $skipMode = $false

    foreach ($line in $lines) {
        if ($line -match "// SPDX-FileCopyrightText:") {
            $skipMode = $true
            continue
        }
        if ($line -match "// SPDX-License-Identifier:") {
            $skipMode = $false
            continue
        }
        if ($skipMode -and $line.Trim() -eq "") {
            continue
        }
        $skipMode = $false
        $newLines += $line
    }

    $newContent = $newLines -join "`n"

    # Build new header with one author per line, sorted by oldest first
    $headerParts = @()
    foreach ($author in $sortedAuthors) {
        $years = $authorYears[$author]
        if ($years.FirstYear -eq $years.LastYear) {
            $yearStr = $years.FirstYear.ToString()
        }
        else {
            $yearStr = "$($years.FirstYear)-$($years.LastYear)"
        }
        $headerParts += "// SPDX-FileCopyrightText: $yearStr $author"
    }
    $headerParts += "// SPDX-License-Identifier: GPL-3.0-only"

    $newHeader = ($headerParts -join "`n") + "`n"

    # Insert new header
    $newContent = $newHeader + $newContent

    # Write back - ensure no BOM
    $utf8NoBom = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($file.FullName, $newContent, $utf8NoBom)
    Write-Host "  Updated with $($sortedAuthors.Count) human authors!"
}

Write-Host "Done!"
