# Script to add SPDX-FileCopyrightText headers - skip bots, merge authors, skip auto-generated, include co-authors
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$env:LANG = "en_US.UTF-8"

$csFiles = Get-ChildItem -Recurse -Filter "*.cs" -File | Where-Object { $_.FullName -notmatch "\\obj\\" }

# Bots to skip - use regex pattern for [bot] suffix
$botsToSkip = @("Copilot", "SourceryAI", "Copilot Autofix powered by AI")
$botPattern = "\[bot\]$"

# Authors to merge (treat as same person)
$authorsToMerge = @{
    "rlauu" = "rlauuzo"
    "Abandoned Cart" = "AbandonedCart"
    "TwistedUmbrellaX" = "AbandonedCart"
}

# Helper function to process an author
function Process-Author {
    param(
        [hashtable]$AuthorYears,
        [string]$Author,
        [string]$Date
    )

    # Skip bots - check exact match and pattern
    if ($botsToSkip -contains $Author -or $Author -match $botPattern) {
        return
    }

    # Merge authors
    if ($authorsToMerge.ContainsKey($Author)) {
        $Author = $authorsToMerge[$Author]
    }

    $year = [int]$Date.Substring(0, 4)

    if (-not $AuthorYears.ContainsKey($Author)) {
        $AuthorYears[$Author] = @{FirstYear = $year; LastYear = $year}
    }
    else {
        if ($year -lt $AuthorYears[$Author].FirstYear) {
            $AuthorYears[$Author].FirstYear = $year
        }
        if ($year -gt $AuthorYears[$Author].LastYear) {
            $AuthorYears[$Author].LastYear = $year
        }
    }
}

foreach ($file in $csFiles) {
    $relativePath = $file.FullName.Replace((Get-Location).Path + "\", "").Replace("\", "/")

    # Check if file starts with auto-generated comment
    $firstLines = Get-Content $file.FullName -Encoding UTF8 -TotalCount 2
    if ($firstLines -match "// <auto-generated />") {
        Write-Host "Skipping auto-generated: $relativePath"
        continue
    }

    Write-Host "Processing: $relativePath"

    # Get all commits with author and date - use UTF-8 encoding
    $commits = git log --follow --format="%an|%ad|%B" --date=short -- $relativePath 2>$null

    # Build a hashmap of author -> year range, merging similar authors
    $authorYears = @{}

    # Process commit lines
    $currentAuthor = ""
    $currentDate = ""
    $messageBuffer = @()

    foreach ($line in $commits) {
        # Check if this is a new commit line (author|date|message)
        if ($line -match '^([^|]+)\|(\d{4}-\d{2}-\d{2})\|(.*)$') {
            # Process previous commit's co-authors from message buffer
            if ($currentAuthor -ne "") {
                $fullMessage = $messageBuffer -join "`n"
                $coAuthors = [regex]::Matches($fullMessage, 'Co-authored-by:\s*([^<]+)<[^>]+>')
                foreach ($coAuthor in $coAuthors) {
                    $coAuthorName = $coAuthor.Groups[1].Value.Trim()
                    Process-Author -AuthorYears $authorYears -Author $coAuthorName -Date $currentDate
                }
            }

            # Start new commit
            $currentAuthor = $matches[1]
            $currentDate = $matches[2]
            $message = $matches[3]
            $messageBuffer = @($message)

            # Process main author (if not a bot)
            if ($botsToSkip -notcontains $currentAuthor) {
                Process-Author -AuthorYears $authorYears -Author $currentAuthor -Date $currentDate
            }
        }
        else {
            # Continue adding to message buffer
            $messageBuffer += $line
        }
    }

    # Process last commit's co-authors
    if ($currentAuthor -ne "") {
        $fullMessage = $messageBuffer -join "`n"
        $coAuthors = [regex]::Matches($fullMessage, 'Co-authored-by:\s*([^<]+)<[^>]+>')
        foreach ($coAuthor in $coAuthors) {
            $coAuthorName = $coAuthor.Groups[1].Value.Trim()
            Process-Author -AuthorYears $authorYears -Author $coAuthorName -Date $currentDate
        }
    }

    # Sort authors by first year (oldest first)
    $sortedAuthors = $authorYears.GetEnumerator() | Sort-Object { $_.Value.FirstYear } | ForEach-Object { $_.Key }

    if ($sortedAuthors.Count -eq 0) {
        Write-Host "  No human authors found, skipping..."
        continue
    }

    Write-Host "  Human authors: $($sortedAuthors.Count)"

    # Read file content
    $content = Get-Content $file.FullName -Raw -Encoding UTF8

    # Remove existing SPDX-FileCopyrightText lines, license line, and Intro-Skipper contributors
    $lines = $content -split "`r?`n"
    $newLines = @()
    $skipMode = $false

    foreach ($line in $lines) {
        if ($line -match "// SPDX-FileCopyrightText:") {
            $skipMode = $true
            continue
        }
        if ($line -match "// SPDX-License-Identifier:") {
            $skipMode = $false
            continue
        }
        if ($skipMode -and $line.Trim() -eq "") {
            continue
        }
        if ($line -match "Intro-Skipper contributors") {
            continue
        }
        $skipMode = $false
        $newLines += $line
    }

    $newContent = $newLines -join "`n"

    # Build new header with one author per line, sorted by oldest first
    $headerParts = @()
    foreach ($author in $sortedAuthors) {
        $years = $authorYears[$author]
        if ($years.FirstYear -eq $years.LastYear) {
            $yearStr = $years.FirstYear.ToString()
        }
        else {
            $yearStr = "$($years.FirstYear)-$($years.LastYear)"
        }
        $headerParts += "// SPDX-FileCopyrightText: $yearStr $author"
    }
    $headerParts += "// SPDX-License-Identifier: GPL-3.0-only"

    $newHeader = ($headerParts -join "`n") + "`n"

    # Insert new header
    $newContent = $newHeader + $newContent

    # Write back - ensure no BOM with CRLF line endings
    $utf8NoBom = New-Object System.Text.UTF8Encoding $false
    # Use CRLF line endings for Windows files
    if ($content -match "`r`n") {
        [System.IO.File]::WriteAllText($file.FullName, $newContent.Replace("`n", "`r`n"), $utf8NoBom)
    }
    else {
        [System.IO.File]::WriteAllText($file.FullName, $newContent, $utf8NoBom)
    }
    Write-Host "  Updated with $($sortedAuthors.Count) human authors!"
}

Write-Host "Done!"
