name: "Bug report"
description: "Create a report to help us improve"
title: "[Bug]: "
labels: [bug]
body:
  - type: checkboxes
    id: requirements
    attributes:
      label: Self service debugging
      description: |
          Jellyfin 10.9 is still being actively updated. Please make sure you are using the newest release

          Docker containers have known permission issues that can be resolved with a few extra steps.
          If your skip button is not shown, please see https://github.com/jumoog/intro-skipper/issues/10
      options:
        - label: Jellyfin is updated and my permissions are correct (or I did not use Docker)
          required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: Also tell us, what did you expect to happen?
      placeholder: |
        The more information that you are able to provide, the better. Did you do anything before this happened? Did you upgrade or change anything? Any screenshots or logs you can provide will be helpful.

        This is my issue.

        Steps to Reproduce
          1. In this environment...
          2. With this config...
          3. Run '...'
          4. See error...
    validations:
      required: true

  - type: input
    attributes:
      label: Jellyfin install method
      description: How you installed Jellyfin or the tool used to install it
      placeholder: Docker, Windows installer, etc.
    validations:
      required: true

  - type: input
    attributes:
      label: Container image/tag or Jellyfin version
      description: The container for Docker or Jellyfin version for a native install
      placeholder: jellyfin/jellyfin:10.8.7, jellyfin-intro-skipper:latest, etc.
    validations:
      required: true

  - type: input
    attributes:
      label: Operating System
      description: The operating system of the Jellyfin / Docker host computer
      placeholder: Debian 11, Windows 11, etc.
    validations:
      required: true

  - type: input
    attributes:
      label: IMDb ID of that TV Series
      placeholder: tt0903747

  - type: textarea
    attributes:
      label: Support Bundle
      placeholder: go to Dashboard -> Plugins -> Intro Skipper -> Support Bundle (at the bottom of the page) and paste the contents of the textbox here
      render: shell
    validations:
      required: true

  - type: textarea
    attributes:
      label: Jellyfin logs
      placeholder: Paste any relevant logs here
      render: shell

