// <auto-generated />
using System;
using IntroSkipper.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntroSkipper.Migrations
{
    [DbContext(typeof(IntroSkipperDbContext))]
    [Migration("20260823080000_AddSegmentProjectionJournal")]
    partial class AddSegmentProjectionJournal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("IntroSkipper.Db.DbAnalyzedState", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "Type");

                    b.ToTable("AnalyzedStates", (string)null);
                });

            modelBuilder.Entity("IntroSkipper.Db.DbDisabledItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("SeasonId");

                    b.ToTable("DisabledItems", (string)null);
                });

            modelBuilder.Entity("IntroSkipper.Db.DbImportRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonStatesImported")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SegmentsImported")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SegmentsSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SourceFileFound")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ImportHistory", (string)null);
                });

            modelBuilder.Entity("IntroSkipper.Db.DbProjectionAttempt", b =>
                {
                    b.Property<Guid>("ChangeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Failure")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChangeId", "ItemId");

                    b.ToTable("ProjectionAttempts", (string)null);
                });

            modelBuilder.Entity("IntroSkipper.Db.DbProjectionExternalOperation", b =>
                {
                    b.Property<Guid>("ChangeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpectedType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExternalSegmentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChangeId", "ItemId", "Position");

                    b.HasIndex("ItemId", "ExternalSegmentId");

                    b.ToTable("ProjectionExternalOperations", (string)null);
                });

            modelBuilder.Entity("IntroSkipper.Db.DbProjectionHead", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastAcceptedSequence")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastAppliedSequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("ProjectionHeads", (string)null);
                });

            modelBuilder.Entity("IntroSkipper.Db.DbProjectionPlan", b =>
                {
                    b.Property<Guid>("ChangeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChangeId", "ItemId");

                    b.HasIndex("ItemId", "Sequence")
                        .IsUnique();

                    b.ToTable("ProjectionPlans", (string)null);
                });

            modelBuilder.Entity("IntroSkipper.Db.DbProjectionPlanSegment", b =>
                {
                    b.Property<Guid>("ChangeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EndTicks")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SegmentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChangeId", "ItemId", "Position");

                    b.ToTable("ProjectionPlanSegments", (string)null);
                });

            modelBuilder.Entity("IntroSkipper.Db.DbSeasonState", b =>
                {
                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("SettledReanalysisEpisodeIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SeasonId", "Type");

                    b.ToTable("SeasonStates", (string)null);
                });

            modelBuilder.Entity("IntroSkipper.Db.DbSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("EndTicks")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "Type", "StartTicks", "EndTicks")
                        .IsUnique()
                        .HasDatabaseName("IX_Segments_ItemId_Type_StartTicks_EndTicks");

                    b.ToTable("Segments", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
