// <auto-generated />
using System;
using IntroSkipper.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntroSkipper.Migrations
{
    [DbContext(typeof(IntroSkipperDbContext))]
    [Migration("20260723120000_AddDisabledEpisodes")]
    partial class AddDisabledEpisodes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("IntroSkipper.Db.DbSeasonState", b =>
                {
                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("EpisodeIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SettledReanalysisEpisodeIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("'[]'");

                    b.HasKey("SeasonId", "Type");

                    b.HasIndex("SeasonId");

                    b.ToTable("DbSeasonState", (string)null);
                });

            modelBuilder.Entity("IntroSkipper.Db.DbDisabledEpisode", b =>
                {
                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.HasKey("SeasonId", "EpisodeId");

                    b.HasIndex("EpisodeId");

                    b.ToTable("DbDisabledEpisode", (string)null);
                });

            modelBuilder.Entity("IntroSkipper.Db.DbSegment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<double>("End")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<bool>("IsUserProvided")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Start")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemId", "Type")
                        .IsUnique()
                        .HasDatabaseName("IX_DbSegment_NonCommercial_Unique")
                        .HasFilter("Type != 4");

                    b.HasIndex("ItemId", "Type", "Start", "End")
                        .IsUnique()
                        .HasDatabaseName("IX_DbSegment_Commercial_Unique")
                        .HasFilter("Type = 4");

                    b.ToTable("DbSegment", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
