// <auto-generated />
using System;
using IntroSkipper.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IntroSkipper.Migrations;

[DbContext(typeof(IntroSkipperDbContext))]
[Migration("20260916120000_AddShortcutAnalysisIdentity")]
partial class AddShortcutAnalysisIdentity
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

        modelBuilder.Entity("IntroSkipper.Db.DbAnalyzedItem", b =>
        {
            b.Property<Guid>("ItemId")
                .HasColumnType("TEXT");

            b.Property<int>("Type")
                .HasColumnType("INTEGER");

            b.Property<string>("ConfigHash")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<long?>("FileVersion")
                .HasColumnType("INTEGER");

            b.Property<string>("ShortcutPath")
                .HasColumnType("TEXT");

            b.Property<double?>("Duration")
                .HasColumnType("REAL");

            b.HasKey("ItemId", "Type");

            b.ToTable("AnalyzedItems", (string)null);
        });
#pragma warning restore 612, 618
    }
}
