// <auto-generated />
using System;
using IntroSkipper.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntroSkipper.Migrations
{
    [DbContext(typeof(IntroSkipperDbContext))]
    [Migration("20260822142139_AnalyzedItems")]
    partial class AnalyzedItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("IntroSkipper.Db.DbAnalyzedItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId", "Type");

                    b.ToTable("AnalyzedItems", (string)null);
                });

            modelBuilder.Entity("IntroSkipper.Db.DbDisabledItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("SeasonId");

                    b.ToTable("DisabledItems", (string)null);
                });

            modelBuilder.Entity("IntroSkipper.Db.DbImportRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonStatesImported")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SegmentsImported")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SegmentsSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SourceFileFound")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ImportHistory", (string)null);
                });

            modelBuilder.Entity("IntroSkipper.Db.DbSeasonState", b =>
                {
                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("SettledReanalysisEpisodeIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SeasonId", "Type");

                    b.ToTable("SeasonStates", (string)null);
                });

            modelBuilder.Entity("IntroSkipper.Db.DbSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("EndTicks")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "Type", "StartTicks", "EndTicks")
                        .IsUnique()
                        .HasDatabaseName("IX_Segments_ItemId_Type_StartTicks_EndTicks");

                    b.ToTable("Segments", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
