// <auto-generated />
using System;
using IntroSkipper.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IntroSkipper.Migrations
{
    [DbContext(typeof(IntroSkipperDbContext))]
    [Migration("20260914090000_AddSeasonAnalysisOverrides")]
    partial class AddSeasonAnalysisOverrides
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("IntroSkipper.Db.DbSeasonAnalysisOverride", b =>
                {
                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AnalysisLengthLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnalysisPercent")
                        .HasColumnType("INTEGER");

                    b.HasKey("SeasonId");

                    b.ToTable("SeasonAnalysisOverrides", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
