export const MINIMUM_ANALYSIS_PERCENT = 1;
export const MAXIMUM_ANALYSIS_PERCENT = 50;
export const MAXIMUM_SETTLED_SEASON_DELAY_HOURS = 87600;
export const MAXIMUM_SETTLED_SEASON_RESCAN_PERIOD_DAYS = 3650;
