<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>IntroSkipper</RootNamespace>
    <AssemblyVersion>1.10.11.17</AssemblyVersion>
    <FileVersion>1.10.11.17</FileVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="IntroSkipper.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.11.*-*" />
    <PackageReference Include="Jellyfin.Model" Version="10.11.*-*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10" />
    <PackageReference Include="SerilogAnalyzer" Version="0.15.0" PrivateAssets="All" />
    <PackageReference Include="SmartAnalyzers.MultithreadingAnalyzer" Version="1.1.31" PrivateAssets="All" />
    <PackageReference Include="StyleCop.Analyzers.Unstable" Version="1.2.0.556" PrivateAssets="All" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Configuration\configPage.html" />
    <EmbeddedResource Include="Configuration\configPage.html" />
    <None Remove="Configuration\introskipper.js" />
    <EmbeddedResource Include="Configuration\introskipper.js" />
    <None Remove="Configuration\introskipper.css" />
    <EmbeddedResource Include="Configuration\introskipper.css" />
  </ItemGroup>
  <Target Name="WebBuild" BeforeTargets="CoreCompile" Condition="'$(SkipWebBuild)' != 'true'">
    <Exec WorkingDirectory="$(MSBuildProjectDirectory)\..\web"
          Command="pnpm install --frozen-lockfile &amp;&amp; pnpm build" />
  </Target>
</Project>
