name: "Build Plugin"

on:
  push:
    branches:
      - '*'  # Triggers on any branch push
    paths-ignore:
      - "**/README.md"
      - ".github/ISSUE_TEMPLATE/**"
      - "docs/**"
      - "images/**"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions:
  contents: write
  packages: write

jobs:
  build:
    if: ${{ ! startsWith(github.event.head_commit.message, 'v0.') }}

    runs-on: ubuntu-latest

    steps:
      - name: Sanitize branch name
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: |
          # Get the branch name and sanitize it
          SANITIZED=$(echo "$HEAD_REF" | sed 's/[^a-zA-Z0-9.-]/_/g')

          # Export it as an environment variable
          echo "SANITIZED_BRANCH_NAME=$SANITIZED" >> $GITHUB_ENV
      - uses: actions/checkout@v7

      - name: Setup build environment
        uses: ./.github/actions/setup-build-env
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Embed version info
        run: |
          GITHUB_SHA=${{ github.sha }}
          sed -i "s/string\.Empty/\"$GITHUB_SHA\"/g" IntroSkipper/Helper/Commit.cs

      - name: Retrieve commit identification
        run: |
          GIT_HASH=$(git rev-parse --short HEAD)
          echo "GIT_HASH=${GIT_HASH}" >> $GITHUB_ENV

      - name: Build
        run: dotnet build --no-restore

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: IntroSkipper-${{ env.GIT_HASH }}.dll
          path: IntroSkipper/bin/Debug/${{ env.DOTNET_TFM }}/IntroSkipper.dll
          if-no-files-found: error

      - name: Create archive
        if: startsWith(github.ref_name, '10.') # only do a preview release on 10.x branches
        run: zip -j "intro-skipper-${{ env.GIT_HASH }}.zip" IntroSkipper/bin/Debug/${{ env.DOTNET_TFM }}/IntroSkipper.dll

      - name: Create/replace the prerelease and upload artifacts
        if: startsWith(github.ref_name, '10.') # only do a preview release on 10.x branches
        run: |
          gh release delete "${{ env.MAIN_VERSION }}/prerelease" --cleanup-tag --yes || true
          gh release create "${{ env.MAIN_VERSION }}/prerelease" "intro-skipper-${{ env.GIT_HASH }}.zip" --prerelease --title "intro-skipper-${{ env.GIT_HASH }}" --notes "This is a prerelease version."  --target ${{ env.MAIN_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
