name: "Run Tests"

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - "**/README.md"
      - ".github/ISSUE_TEMPLATE/**"
      - "docs/**"
      - "images/**"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Read build configuration
        id: read-config
        run: |
          CONFIG=$(cat build.json)
          echo "IS_BETA=$(echo "$CONFIG" | jq -r '.beta')" >> $GITHUB_ENV
          echo "DOTNET_VERSION=$(echo "$CONFIG" | jq -r '."dotnet-version"')" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install jellyfin-ffmpeg
        run: |
          sudo apt update
          curl -fsSLO https://github.com/jellyfin/jellyfin-ffmpeg/releases/download/v7.1.3-1/jellyfin-ffmpeg7_7.1.3-1-noble_amd64.deb
          sudo apt install -y ./jellyfin-ffmpeg7_7.1.3-1-noble_amd64.deb
          sudo ln -s /usr/lib/jellyfin-ffmpeg/ffmpeg /usr/local/bin/ffmpeg
          sudo ln -s /usr/lib/jellyfin-ffmpeg/ffprobe /usr/local/bin/ffprobe
          ffmpeg -version

      - name: Configure NuGet for beta
        if: ${{ env.IS_BETA == 'true' }}
        run: |
          cp nuget/NuGet.Beta.Config IntroSkipper/NuGet.Config
          dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github-jellyfin "https://nuget.pkg.github.com/jellyfin/index.json"
          dotnet tool install --global dotnet-outdated-tool
          dotnet outdated -pre Always -u -inc Jellyfin

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal
